const greenPocket = { backgroundColor: "green" };
const redPocket = { backgroundColor: "red" };
const blackPocket = { backgroundColor: "black" };

export const roulettePockets = [
	{ option: "0", style: greenPocket },
	{ option: "32", style: redPocket },
	{ option: "15", style: blackPocket },
	{ option: "19", style: redPocket },
	{ option: "4", style: blackPocket },
	{ option: "21", style: redPocket },
	{ option: "2", style: blackPocket },
	{ option: "25", style: redPocket },
	{ option: "17", style: blackPocket },
	{ option: "34", style: redPocket },
	{ option: "6", style: blackPocket },
	{ option: "27", style: redPocket },
	{ option: "13", style: blackPocket },
	{ option: "36", style: redPocket },
	{ option: "11", style: blackPocket },
	{ option: "30", style: redPocket },
	{ option: "8", style: blackPocket },
	{ option: "23", style: redPocket },
	{ option: "10", style: blackPocket },
	{ option: "5", style: redPocket },
	{ option: "24", style: blackPocket },
	{ option: "16", style: redPocket },
	{ option: "33", style: blackPocket },
	{ option: "1", style: redPocket },
	{ option: "20", style: blackPocket },
	{ option: "14", style: redPocket },
	{ option: "31", style: blackPocket },
	{ option: "9", style: redPocket },
	{ option: "22", style: blackPocket },
	{ option: "18", style: redPocket },
	{ option: "29", style: blackPocket },
	{ option: "7", style: redPocket },
	{ option: "28", style: blackPocket },
	{ option: "12", style: redPocket },
	{ option: "35", style: blackPocket },
	{ option: "3", style: redPocket },
	{ option: "26", style: blackPocket },
];
